description: LSSTCam Photon-Transfer Curve calibration construction.
instrument: lsst.obs.lsst.LsstCam
imports:
  - location: /sdf/home/a/abrought/run6/config/pipelines/cpPtc_base.yaml
tasks:
  ptcIsr:
    class: lsst.ip.isr.IsrTask
    config:
      doDeferredCharge: true
      deferredChargeCorrection.useGains: false
  ptcExtract:
    class: lsst.cp.pipe.ptc.PhotonTransferCurveExtractTask
    config:
      edgeMaskLevel: AMP
      numEdgeSuspect: 20
      doExtractPhotodiodeData: true
      auxiliaryHeaderKeys: ["CCOBCURR", "CCOBFLUX"]
      matchExposuresType: FLUX
